spring.datasource.url=jdbc:postgresql://localhost:5432/db_stock

spring.datasource.username=postgres
spring.datasource.password=B.fcosta123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

stock.low-threshold.default=5